// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjVLbYDTrnJPaXF23C5ScCD0JnWPnZCFQ',
    appId: '1:663488381235:web:c0f7a7ea3d64dbc4b57e46',
    messagingSenderId: '663488381235',
    projectId: 'lms-learning-management-ce88b',
    authDomain: 'lms-learning-management-ce88b.firebaseapp.com',
    storageBucket: 'lms-learning-management-ce88b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcM1oOgCz9iSNUySayxJgVkmR5Aa80euQ',
    appId: '1:663488381235:android:a425b160debee040b57e46',
    messagingSenderId: '663488381235',
    projectId: 'lms-learning-management-ce88b',
    storageBucket: 'lms-learning-management-ce88b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDRexnLA9rUjUrrX0p1Sdye_CFhahoLVw',
    appId: '1:663488381235:ios:1fdb43430f18917cb57e46',
    messagingSenderId: '663488381235',
    projectId: 'lms-learning-management-ce88b',
    storageBucket: 'lms-learning-management-ce88b.firebasestorage.app',
    iosBundleId: 'com.example.learningManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDRexnLA9rUjUrrX0p1Sdye_CFhahoLVw',
    appId: '1:663488381235:ios:1fdb43430f18917cb57e46',
    messagingSenderId: '663488381235',
    projectId: 'lms-learning-management-ce88b',
    storageBucket: 'lms-learning-management-ce88b.firebasestorage.app',
    iosBundleId: 'com.example.learningManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjVLbYDTrnJPaXF23C5ScCD0JnWPnZCFQ',
    appId: '1:663488381235:web:498c3dcaac16c929b57e46',
    messagingSenderId: '663488381235',
    projectId: 'lms-learning-management-ce88b',
    authDomain: 'lms-learning-management-ce88b.firebaseapp.com',
    storageBucket: 'lms-learning-management-ce88b.firebasestorage.app',
  );
}
