@startuml state_diagram

[*] --> LoggedOut

LoggedOut --> LoggedIn : Login
LoggedIn --> BrowsingCourses
BrowsingCourses --> Enrolled : Enroll
Enrolled --> WatchingLecture
WatchingLecture --> TakingQuiz
TakingQuiz --> ViewingPerformance
ViewingPerformance --> LoggedOut : Logout

@enduml